### PR TITLE
Fix regression from #1412

### LINKED ISSUE #1420: Adding Autocomplete results to "t.querySelectorAll is not a function"
### Description:
When i simply add a new Autocomplete with Form Builder an error appears.

### Environment Details:

 - formBuilder Version: 3.10.0
 - Browser: Mozilla
 - OS: Windows 10

### Actual Behavior
t.querySelectorAll is not a function

### Steps to Reproduce
- In Form Builder click on "Autocomplete" to add a new autocomplete

### Screenshot - *(optional)*

image

### PR DESCRIPTION
**Pull request by lucasnetau**
Autocomplete builds the field config as an Array of HTMLElements, handle this case when processing the className

Fixes #1420

### CODE REVIEW

**Comment by lucasnetau** [comment]
This was not picked up in automated tested due to the addField action takes a different code path to clicking on the control in the panel. When adding via the control panel className is set to 'form-control' 

```javascript
    if (isNew && ['text', 'number', 'file', 'date', 'select', 'textarea', 'autocomplete'].includes(field.type)) {
      field.className = field.className || 'form-control'
    }
```

however when adding via addField this is not performed. Without a className being set the code issue fixed by the PR is not triggered.

Have added test cases adding fields via simulated Click events

**Review by kevinchappell — APPROVED** [review]
